baseurl = "http://gccnus.org/"
title = "Global China Connection"
theme = "ghostwriter"
languageCode = "en-us"
copyright = "Yuri Jhou"
disqusShortname = "XXX"
googleAnalytics = "XXX"

[Author]
    name = "Yuri Jhou"
    profile = "https://google.com/+XXX"

[Taxonomies]
    tag = "tags"

[Params]
    intro = true
    headline = "Global China Connection "
    description = "in National University of Singapore"
    github = "https://github.com/XXX"
    linkedin = "https://linkedin.com/in/XXX/"
    gplus = "https://google.com/+XXX"
    twitter = "https://twitter.com/XXX"
    stackoverflow = "http://stackoverflow.com/users/XXX/YYY"

[Permalinks]
    post = "/:year/:month/:day/:filename/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Projects"
    url = "/project/"
    weight = 2

[[menu.main]]
    name = "Contact"
    url = "/page/contact/"
    weight = 3

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 4

[[menu.main]]
		name = "Gallery"
		url="/gallery/"
		weight = 5